/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bhaskar
 */
public class tttframe extends javax.swing.JFrame {

    /**
     * Creates new form tttframe
     */int mode;
     int isdone=0;
     
        String playerone;
        String playertwo;
        int mycheck=0;
    public tttframe() {
        
        playerone="X";
        playertwo="O";
        mode=1;
        
        
        initComponents();
        turn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("TIC TAC TOE");

        jButton10.setText("Turn");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton1.getText().equalsIgnoreCase(""))
            {
            jButton1.setText(playerone);
            mode=2;turn();
            mycheck++;
            check();
            
            
            }
            }
            
        }
        else 
        {
            if(isdone==0)
            {
            if(jButton1.getText().equalsIgnoreCase(""))
            {
            jButton1.setText(playertwo);
            mode=1;turn();
            mycheck++;
            check();
            }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(isdone==0)
            {
         if(mode==1)
        {
            if(jButton2.getText().equalsIgnoreCase(""))
            {
            jButton2.setText(playerone);
            mode=2;turn();mycheck++;
            check();
            }
        }
            }
        else
        {
            if(isdone==0)
            {
            if(jButton2.getText().equalsIgnoreCase(""))
            {
            jButton2.setText(playertwo);
            mode=1;turn();mycheck++;
            check();
            }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton3.getText().equalsIgnoreCase(""))
            {
            jButton3.setText(playerone);
            mode=2;turn();mycheck++;
            check();
            }
            }
        }
        else
        {
            if(isdone==0)
            {
            if(jButton3.getText().equalsIgnoreCase(""))
            {
            jButton3.setText(playertwo);
            mode=1;turn();mycheck++;
            check();
            }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(isdone==0)
            {
         if(mode==1)
        {
            if(jButton4.getText().equalsIgnoreCase(""))
            {
            jButton4.setText(playerone);
            mode=2;turn();mycheck++;
            check();
            }
        }}
        else
        {
            if(isdone==0)
            {
            if(jButton4.getText().equalsIgnoreCase(""))
            {
            jButton4.setText(playertwo);
            mode=1;turn();mycheck++;
            check();
            }}
           
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton5.getText().equalsIgnoreCase(""))
            {
            jButton5.setText(playerone);
            mode=2;turn();mycheck++;
            check();
            }}
        }
        else
        {
            if(isdone==0)
            {
            if(jButton5.getText().equalsIgnoreCase(""))
            {
            jButton5.setText(playertwo);
            mode=1;turn();mycheck++;
            check();
            }
            }
           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton6.getText().equalsIgnoreCase(""))
            {
            jButton6.setText(playerone);
            mode=2;turn();mycheck++;
            check();
            }
            }
        }
        else
        {
            if(isdone==0)
            {
            if(jButton6.getText().equalsIgnoreCase(""))
            {
            jButton6.setText(playertwo);
            mode=1;turn();mycheck++;
            check();
            }
            }
          
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton7.getText().equalsIgnoreCase(""))
            {
            jButton7.setText(playerone);
            mode=2;
            turn();mycheck++;
            check();
            }}
        }
        else
        {
            if(isdone==0)
            {
            if(jButton7.getText().equalsIgnoreCase(""))
            {
            jButton7.setText(playertwo);
            mode=1;
            turn();mycheck++;
            check();
            }}
           
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {
            if(isdone==0)
            {
            if(jButton8.getText().equalsIgnoreCase(""))
            {
            jButton8.setText(playerone);
            mode=2;
            turn();mycheck++;
            check();
            }}
        }
        else
        {
            if(isdone==0)
            {
            if(jButton8.getText().equalsIgnoreCase(""))
            {
            jButton8.setText(playertwo);
            mode=1;
            turn();mycheck++;
            check();
            }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         if(mode==1)
        {if(isdone==0)
            {
            if(jButton9.getText().equalsIgnoreCase(""))
            {
            jButton9.setText(playerone);
            mode=2;
            turn();mycheck++;
            check();
            }}
        }
        else
        {if(isdone==0)
            {
            if(jButton9.getText().equalsIgnoreCase(""))
            {
            jButton9.setText(playertwo);
            mode=1;
            turn();mycheck++;
            check();
            
            }}
            
        }
         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton10ActionPerformed
    public void check()
    {
        //from button one
            if(jButton1.getText().equalsIgnoreCase(playerone))
                if(jButton2.getText().equalsIgnoreCase(playerone))
                    if(jButton3.getText().equalsIgnoreCase(playerone))
                            func(1);
            
            if(jButton4.getText().equalsIgnoreCase(playerone))
                if(jButton5.getText().equalsIgnoreCase(playerone))
                    if(jButton6.getText().equalsIgnoreCase(playerone))
                            func(1);
        
            if(jButton7.getText().equalsIgnoreCase(playerone))
                if(jButton8.getText().equalsIgnoreCase(playerone))
                    if(jButton9.getText().equalsIgnoreCase(playerone))
                            func(1);
        
            if(jButton1.getText().equalsIgnoreCase(playerone))
                if(jButton4.getText().equalsIgnoreCase(playerone))
                    if(jButton7.getText().equalsIgnoreCase(playerone))
                            func(1);
            
            if(jButton2.getText().equalsIgnoreCase(playerone))
                if(jButton5.getText().equalsIgnoreCase(playerone))
                    if(jButton8.getText().equalsIgnoreCase(playerone))
                            func(1);
            
            if(jButton3.getText().equalsIgnoreCase(playerone))
                if(jButton6.getText().equalsIgnoreCase(playerone))
                    if(jButton9.getText().equalsIgnoreCase(playerone))
                            func(1);
            
            if(jButton1.getText().equalsIgnoreCase(playerone))
                if(jButton5.getText().equalsIgnoreCase(playerone))
                    if(jButton9.getText().equalsIgnoreCase(playerone))
                            func(1);
            
            if(jButton3.getText().equalsIgnoreCase(playerone))
                if(jButton5.getText().equalsIgnoreCase(playerone))
                    if(jButton7.getText().equalsIgnoreCase(playerone))
                            func(1);
            //++++++++++++++++++++++++++++++++++++++++++++++++++++
            if(jButton1.getText().equalsIgnoreCase(playertwo))
                if(jButton2.getText().equalsIgnoreCase(playertwo))
                    if(jButton3.getText().equalsIgnoreCase(playertwo))
                            func(2);
            
            if(jButton4.getText().equalsIgnoreCase(playertwo))
                if(jButton5.getText().equalsIgnoreCase(playertwo))
                    if(jButton6.getText().equalsIgnoreCase(playertwo))
                            func(2);
        
            if(jButton7.getText().equalsIgnoreCase(playertwo))
                if(jButton8.getText().equalsIgnoreCase(playertwo))
                    if(jButton9.getText().equalsIgnoreCase(playertwo))
                            func(2);
        
            if(jButton1.getText().equalsIgnoreCase(playertwo))
                if(jButton4.getText().equalsIgnoreCase(playertwo))
                    if(jButton7.getText().equalsIgnoreCase(playertwo))
                            func(2);
            
            if(jButton2.getText().equalsIgnoreCase(playertwo))
                if(jButton5.getText().equalsIgnoreCase(playertwo))
                    if(jButton8.getText().equalsIgnoreCase(playertwo))
                            func(2);
            
            if(jButton3.getText().equalsIgnoreCase(playertwo))
                if(jButton6.getText().equalsIgnoreCase(playertwo))
                    if(jButton9.getText().equalsIgnoreCase(playertwo))
                            func(2);
            
            if(jButton1.getText().equalsIgnoreCase(playertwo))
                if(jButton5.getText().equalsIgnoreCase(playertwo))
                    if(jButton9.getText().equalsIgnoreCase(playertwo))
                            func(2);
            
            if(jButton3.getText().equalsIgnoreCase(playertwo))
                if(jButton5.getText().equalsIgnoreCase(playertwo))
                    if(jButton7.getText().equalsIgnoreCase(playertwo))
                            func(2);
            if(mycheck==9)
            {
                isdone=1;
                jButton10.setText("DRaw");
                System.out.println("Draw");
                //System.exit(6);
            }
            
    }
    
    public void func(int player){
        if(player == 2)
        {
            jButton10.setText("player two won");
               System.out.println("player two wins");
                //newclass nc = new newclass(2);
                //nc.run();
              // if(isdone == 0)
               
        }
        
                              
        else
        {
            jButton10.setText("player one won");
            System.out.println("player one wins");
        //newclass nc = new newclass(1);
            //nc.run();
        }
        isdone=1;
         //System.exit(6);
         
    //tft.setVisible(false);
    }
    
    public void turn(){
        if(mode == 1){
            jButton10.setText("playerone");
            
        }else
            jButton10.setText("playertwo");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tttframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tttframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tttframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tttframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new tttframe().setVisible(true);
                tttframe tft=new tttframe();
                tft.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
